#!/bin/sh
eww_bar_config="$HOME/.config/eww/right-bar"
monitor_count=$(xrandr --listactivemonitors | head -n 1 | awk '{print $2}')

for i in $(seq 0 "$((monitor_count - 1))"); do
	echo "Closing eww right-bar-$i on monitor $i"
	eww -c "$eww_bar_config" close "right-bar-$i"
done
