#!/bin/bash

is_charging=$(batstatus --status)
charge=$(batstatus --total)
charge_full=84 # 85-100 is considered full to me

icon()
{
	if [ "$is_charging" = 'Charging' ] && [ "$charge" -lt "$charge_full" ]; then
		echo "images/icons/battery/charging.png"
	elif [ "$charge" -gt "$charge_full" ]; then
		echo "images/icons/battery/full.png"
	else
		if [ "$charge" -gt 50 ]; then
			echo "images/icons/battery/battery-3.png"
		elif [ "$charge" -gt 25 ]; then
			echo "images/icons/battery/battery-2.png"
		elif [ "$charge" -gt 9 ]; then
			echo "images/icons/battery/battery-1.png"
		else
			echo "images/icons/battery/low.png"
		fi
	fi
}

icon
