-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.permission({ binary = "/usr/(bin|local/bin)/hyprpm", type = "plugin", allow = "allow" })

--############################
--## ENVIRONMENT VARIABLES ###
--############################

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("HYPR_PLUGIN_DIR", "/home/lucca/.config/hypr/plugins")

--####################
--## LOOK AND FEEL ###
--####################

hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 3,
    bezier = "default",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 3,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 3,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 3,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 3,
    bezier = "default",
})

-- TODO: manual review — plugin section ''. The new Lua API exposes plugins via hl.plugin.<name>(...) — wire up per the plugin's docs.
--[[
  hyprbars { ... }
  hyprmodoro { ... }
]]

local mod = "SUPER" -- Sets "Windows" key as main modifier

hl.bind(mod .. " + RETURN", hl.dsp.exec_cmd("$TERMINAL"))
hl.bind(mod .. " + Q", hl.dsp.window.close())
hl.bind(mod .. " + SHIFT + Q", hl.dsp.exit())
hl.bind(mod .. " + SHIFT + S", hl.dsp.exec_cmd("powermenu"))
hl.bind(mod .. " + F", hl.dsp.exec_cmd("$TERMINAL -e yazi"))
hl.bind(mod .. " + CTRL + SPACE", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + CTRL + RETURN", hl.dsp.exec_cmd("toggle_sidebar"))
hl.bind(mod .. " + SHIFT + B", hl.dsp.exec_cmd("toggle_status_bar"))
hl.bind(mod .. " + B", hl.dsp.exec_cmd("lockscreen"))
hl.bind(mod .. " + SPACE", hl.dsp.exec_cmd("rofi -show drun -show-icons"))
hl.bind(mod .. " + SHIFT + SPACE", hl.dsp.exec_cmd("rofi -show run -show-icons"))
hl.bind(mod .. " + V", hl.dsp.exec_cmd("~/.config/hypr/scripts/window_finder.sh"))
hl.bind(mod .. " + SHIFT + M", hl.dsp.exec_cmd("rofi -show calc -modi calc -no-show-match -no-sort -theme ~/.config/rofi/calc.rasi"))
hl.bind(mod .. " + W", hl.dsp.exec_cmd("$BROWSER --disable-features=WaylandWpColorManagerV1"))

hl.bind(mod .. " + T", hl.dsp.exec_cmd("dunstctl set-paused toggle"))

hl.bind(mod .. " + SHIFT + RETURN", hl.dsp.layout("swapwithmaster"))
hl.bind(mod .. " + SEMICOLON", hl.dsp.exec_cmd("~/.config/hypr/scripts/toggle_layout.sh"))
hl.bind(mod .. " + SHIFT + SEMICOLON", hl.dsp.exec_cmd("~/.config/hypr/scripts/toggle_layout.sh prev"))
hl.bind(mod .. " + M", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))

hl.bind(mod .. " + CTRL + R", hl.dsp.exec_cmd("hyprctl reload"))

hl.bind(mod .. " + F1", hl.dsp.exec_cmd("sound_control -t"))
hl.bind(mod .. " + F2", hl.dsp.exec_cmd("$TERMINAL --class floats -e pulsemixer"))
hl.bind(mod .. " + F10", hl.dsp.exec_cmd("toggle_redshift"))
hl.bind(mod .. " + F11", hl.dsp.exec_cmd("killall btop || $TERMINAL -e btop"))

hl.bind(mod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mod .. " + J", hl.dsp.focus({ direction = "down" }))
hl.bind(mod .. " + SHIFT + H", hl.dsp.window.swap({ direction = "l" }))
hl.bind(mod .. " + SHIFT + L", hl.dsp.window.swap({ direction = "r" }))
hl.bind(mod .. " + SHIFT + K", hl.dsp.window.swap({ direction = "u" }))
hl.bind(mod .. " + SHIFT + J", hl.dsp.window.swap({ direction = "d" }))
hl.bind(mod .. " + C", hl.dsp.window.cycle_next({ next = true }))
hl.bind(mod .. " + Tab", hl.dsp.window.cycle_next({ next = true }))

hl.bind(mod .. " + 1", hl.dsp.exec_cmd("hypr_workspace_manager 1"))
hl.bind(mod .. " + 2", hl.dsp.exec_cmd("hypr_workspace_manager 2"))
hl.bind(mod .. " + 3", hl.dsp.exec_cmd("hypr_workspace_manager 3"))
hl.bind(mod .. " + 4", hl.dsp.exec_cmd("hypr_workspace_manager 4"))
hl.bind(mod .. " + 5", hl.dsp.exec_cmd("hypr_workspace_manager 5"))
hl.bind(mod .. " + 6", hl.dsp.exec_cmd("hypr_workspace_manager 6"))
hl.bind(mod .. " + 7", hl.dsp.exec_cmd("hypr_workspace_manager 7"))
hl.bind(mod .. " + 8", hl.dsp.exec_cmd("hypr_workspace_manager 8"))
hl.bind(mod .. " + 9", hl.dsp.exec_cmd("hypr_workspace_manager 9"))
hl.bind(mod .. " + 0", hl.dsp.exec_cmd("hypr_workspace_manager 10"))

hl.bind(mod .. " + SHIFT + 1", hl.dsp.exec_cmd("hypr_workspace_manager move 1"))
hl.bind(mod .. " + SHIFT + 2", hl.dsp.exec_cmd("hypr_workspace_manager move 2"))
hl.bind(mod .. " + SHIFT + 3", hl.dsp.exec_cmd("hypr_workspace_manager move 3"))
hl.bind(mod .. " + SHIFT + 4", hl.dsp.exec_cmd("hypr_workspace_manager move 4"))
hl.bind(mod .. " + SHIFT + 5", hl.dsp.exec_cmd("hypr_workspace_manager move 5"))
hl.bind(mod .. " + SHIFT + 6", hl.dsp.exec_cmd("hypr_workspace_manager move 6"))
hl.bind(mod .. " + SHIFT + 7", hl.dsp.exec_cmd("hypr_workspace_manager move 7"))
hl.bind(mod .. " + SHIFT + 8", hl.dsp.exec_cmd("hypr_workspace_manager move 8"))
hl.bind(mod .. " + SHIFT + 9", hl.dsp.exec_cmd("hypr_workspace_manager move 9"))
hl.bind(mod .. " + SHIFT + 0", hl.dsp.exec_cmd("hypr_workspace_manager move 10"))

hl.bind(mod .. " + O", hl.dsp.exec_cmd("hypr_workspace_manager other"))

hl.bind(mod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mod .. " + N", hl.dsp.window.move({ workspace = "special:magic" }))
hl.bind(mod .. " + N", hl.dsp.workspace.toggle_special("magic"))

hl.bind(mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize())

hl.bind("Print", hl.dsp.exec_cmd("screenshot"), { locked = true, repeating = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("sound_control u"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("sound_control d"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("sound_control m"), { locked = true, repeating = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("sound_control t"), { locked = true, repeating = true })
hl.bind("XF86Launch1", hl.dsp.exec_cmd("sound_control t"), { locked = true, repeating = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 5%+"), { locked = true, repeating = true })
hl.bind(mod .. " + ALT + +", hl.dsp.exec_cmd("brightnessctl s 5%+"))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 5%-"), { locked = true, repeating = true })
hl.bind(mod .. " + ALT + -", hl.dsp.exec_cmd("brightnessctl s 5%+"))

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind(mod .. " + ALT + period", hl.dsp.exec_cmd("playerctl next"))

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind(mod .. " + ALT + P", hl.dsp.exec_cmd("playerctl play-pause"))

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind(mod .. " + ALT + comma", hl.dsp.exec_cmd("playerctl previous"))

hl.bind(mod .. " + SHIFT + C", hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy"))

hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("lockscreen"), { locked = true })
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("systemctl suspend"), { locked = true })
hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("setup_workspace"), { locked = true })

hl.window_rule({
    match = {
        class = ".*Floating.*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = ".*floats.*",
    },
    float = true,
})

hl.window_rule({
    match = {
        initial_class = ".*zoom.*",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = ".*floats.*",
    },
    size = "35% 60%",
})

hl.window_rule({
    match = {
        class = ".*Tasklist.*",
    },
    move = "(20) (100)",
})

hl.window_rule({
    match = {
        initial_class = ".*Tasklist.*",
    },
    float = true,
    size = "35% 60%",
})

hl.window_rule({
    match = {
        class = ".*Authenticator.*",
    },
    float = true,
    size = "35% 60%",
})

hl.window_rule({
    match = {
        initial_class = ".*io.ente.auth.*",
    },
    move = "(20) (100)",
    float = true,
    size = "35% 60%",
})

hl.window_rule({
    match = {
        initial_title = ".*pulsemixer.*",
    },
    size = "60% 35%",
})

hl.window_rule({
    match = {
        initial_class = ".*blueman-manager.*",
    },
    float = true,
    size = "15% 15%",
})

hl.window_rule({
    match = {
        class = "(Rofi)",
    },
    pin = true,
})

hl.window_rule({
    match = {
        title = "^(flameshot)",
    },
    float = true,
    move = "0 0",
    suppress_event = "fullscreen",
})

hl.window_rule({
    match = {
        initial_class = ".*firefox.*",
    },
    workspace = "2",
})

hl.window_rule({
    match = {
        initial_class = ".*Vivaldi.*",
    },
    workspace = "2",
})

hl.window_rule({
    match = {
        initial_class = ".*brave.*",
    },
    workspace = "2",
})

hl.window_rule({
    match = {
        initial_class = ".*qutebrowser.*",
    },
    workspace = "2",
})

hl.window_rule({
    match = {
        initial_class = ".*Gimp.*",
    },
    workspace = "3 silent",
})

hl.window_rule({
    match = {
        initial_class = ".*Telegram.*",
    },
    workspace = "4 silent",
})

hl.window_rule({
    match = {
        initial_class = ".*Ferdium.*",
    },
    workspace = "4 silent",
})

hl.window_rule({
    match = {
        initial_class = ".*[Tt]hunderbird.*",
    },
    workspace = "4 silent",
})

hl.window_rule({
    match = {
        initial_class = ".*zoom.*",
    },
    workspace = "5 silent",
})

hl.window_rule({
    match = {
        initial_class = ".*discord.*",
    },
    workspace = "6 silent",
})

hl.window_rule({
    match = {
        initial_class = ".*slack.*",
    },
    workspace = "6 silent",
})

hl.window_rule({
    match = {
        initial_class = ".*Slack.*",
    },
    workspace = "6 silent",
})

hl.window_rule({
    match = {
        initial_class = ".*transmission.*",
    },
    workspace = "8 silent",
})

hl.window_rule({
    match = {
        initial_class = ".*DBeaver.*",
    },
    workspace = "9",
})

hl.window_rule({
    match = {
        initial_class = ".*Spotify.*",
    },
    workspace = "10",
})

hl.window_rule({
    match = {
        initial_class = ".*spotify.*",
    },
    workspace = "10",
})

hl.window_rule({
    match = {
        initial_class = ".*elisa.*",
    },
    workspace = "10",
})

hl.window_rule({
    match = {
        initial_class = ".*org.gnome.clocks.*",
    },
    workspace = "10 silent",
})

hl.window_rule({
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@120.00",
    position = "0x0",
    scale = "1.00",
})

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60.00",
    position = "1920x0",
    scale = "1.00",
})

hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60.00",
    position = "3840x0",
    scale = "1.00",
})

hl.config({
    general = {
        gaps_in = 10,
        gaps_out = 20,
        border_size = 3,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        -- col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
        col = {
            active_border = { colors = { "rgba(7a0e6aee)", "rgba(541140ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "scrolling",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#decoration
    decoration = {
        rounding = 12,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 0.95,
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = false,
            size = 3,
            passes = 1,
            vibrancy = 0.1696,
        },
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#animations
    animations = {
        enabled = true,
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
        -- bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    },
    -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    dwindle = {
        preserve_split = false,
        force_split = 2,
    },
    -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    master = {
        new_status = "slave",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#misc
    misc = {
        force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
    debug = {
        disable_logs = false,
    },
    --############
    --## INPUT ###
    --############
    -- https://wiki.hyprland.org/Configuring/Variables/#input
    input = {
        kb_layout = "us,br",
        kb_options = "grp:alt_shift_toggle",
        follow_mouse = 1,
        float_switch_override_focus = 1,
        sensitivity = 0.3, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = true,
            disable_while_typing = false,
        },
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#gestures
    -- gestures {
    --     workspace_swipe = false
    -- }
    scrolling = {
        fullscreen_on_one_column = 1,
        column_width = 0.7,
        focus_fit_method = 1, -- 0 centers the focused window, 1 fits
        follow_min_visible = 0.1,
    },
    --##################
    --## KEYBINDINGS ###
    --##################
    -- See https://wiki.hyprland.org/Configuring/Keywords/
    -- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
    -- Minimize by putting in special workspace
    -- bind = $mod, N, togglespecialworkspace, magic
    -- bind = $mod, N, movetoworkspace, +0
    -- bind = $mod, N, togglespecialworkspace, magic
    -- bind = $mod, N, movetoworkspace, special:magic
    -- bind = $mod, N, togglespecialworkspace, magic
    -- Move focus with mod + arrow keys
    -- Switch workspaces with mod + [0-9]
    -- Move active window to a workspace with mod + SHIFT + [0-9]
    -- Example special workspace (scratchpad)
    -- Scroll through existing workspaces with mod + scroll
    -- Move/resize windows with mod + LMB/RMB and dragging
    -- Laptop multimedia keys for volume and LCD brightness
    -- mic mute is useless for me set it to toggle the default audio source
    -- Requires playerctl
    -- Clipboard manager
    --#############################
    --##        SWITCHES        ###
    --#############################
    -- Trigger when the switch is toggled.
    -- Trigger when the switch is turning on.
    -- Trigger when the switch is turning off.
    --#############################
    --## WINDOWS AND WORKSPACES ###
    --#############################
    -- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
    -- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
    -- windowrule = workspace 3 silent, match:initial_class .*krita.*
    -- windowrule = workspace 3 silent, match:initial_class .*shotcut.*
})

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=hyprland")
    hl.exec_cmd("sleep 1 && setup_workspace")
    hl.exec_cmd("startup_progs")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
end)

