#!/bin/sh

disk_usage=$(df -h | grep home)
disk_usage_percentage=$(echo "$disk_usage" | awk '{print $5}')
disk_usage_percentage=${disk_usage_percentage%%%*}

sound_cards_info=$(pactl -f json list cards | sound_manager -f)
profile="{\"hostname\": \"$(hostname)\", \"uptime\": \"$(uptime -p)\", \"user\": \"$(whoami)\"}"

info="{ \
	\"disk\": { \
		\"size\": \"$(echo "$disk_usage" | awk '{print $2}')\", \
		\"used\": \"$(echo "$disk_usage" | awk '{print $3}')\", \
		\"free\": \"$(echo "$disk_usage" | awk '{print $4}')\", \
		\"percentage\": \"$disk_usage_percentage\" \
	}, \
	\"sound\": ${sound_cards_info},\
	\"profile\": ${profile}\
}"

echo "$info" | sed 's/\t//g'
