#!/usr/bin/env sh

config="$HOME/.config/eww/sidebar/"
lock_file="/tmp/eww_sidebar_open"
screens_resolutions=$(sh "$config/scripts/screen_resolutions")

get_current_monitor()
{
	current_monitor="1"
	if [ "$(pgrep awesome)" ]; then
		current_monitor="$(awesome-client 'return mouse.screen.index' | cut -d ' ' -f 5)"
		current_monitor=$((current_monitor - 1))
	#elif bspwm; then
		# TODO: make it work for other wms
	elif [ "$(pgrep Hyprland)" ]; then
		current_monitor=$(hyprctl -j monitors  | jq '.[] | select(.focused) | .id')
	fi
	echo "$current_monitor"
}

run_eww() {
	monitor=$(get_current_monitor)
	echo $monitor
	eww -c "$config" open-many \
		sidebar:sidebar \
		quotes:quotes \
		--arg sidebar:screen="$monitor" \
		--arg sidebar:screens_resolutions="$screens_resolutions" \
		--arg quotes:screen="$monitor" \
		--arg quotes:screens_resolutions="$screens_resolutions"
}

if [ ! -f "$lock_file" ]; then
	touch "$lock_file"
	touch /tmp/sound_control_status
	run_eww
else
	rm "$lock_file" &&
	eww -c "$config" close-all
fi
