#!/bin/python

#from sys import stdin
from json import dumps

import subprocess
workspaces = subprocess.run(
    ["wmctrl", "-d"],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
).stdout.decode('utf8').strip()

windows_on_workspaces = (
    subprocess.run(
        ["wmctrl", "-lx"],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    .stdout.decode()
    .strip()
)

# workspace_info = "".join(stdin.readlines())
# windows_on_workspaces, workspaces = workspace_info.split("--|--")

workspace_list = workspaces.split("\n")

active_workspaces = [int(w[10:13]) for w in windows_on_workspaces.split("\n") if w]
workspace_labels = [w.split(' ').pop() for w in workspace_list]
current_workspace = int([w.split(' ')[0] for w in workspace_list if "*" in w][0])

workspaces_by_monitor = {}
workspaces_by_monitor["open"] = []
workspaces_by_monitor["open_in_monitor"] = -1

open_windows_info = [w for w in windows_on_workspaces.split("\n") if f" {current_workspace} " in w]
if len(open_windows_info) > 0:
    open_windows = [
        {
            "id": w.split(" ")[0],
            "name": [s for s in w.split(" ") if s != ""][2]
            .split(".")
            .pop(),  # handle possible double spaces that fuck up the split on ' '
        }
        for w in open_windows_info
    ]
    workspaces_by_monitor["open"] = open_windows

for index, label in enumerate(workspace_labels):
    monitor = index // 10
    if monitor not in workspaces_by_monitor:
        workspaces_by_monitor[monitor] = []

    class_name = "current" if index == current_workspace else "active" if index in active_workspaces else "empty"

    workspaces_by_monitor[monitor].append({
        "class": class_name,
        "index": index,
        "label": label
    })

    if class_name == "current":
        workspaces_by_monitor["open_in_monitor"] = monitor


print(dumps(workspaces_by_monitor, ensure_ascii=False))

# shell script version
#!/bin/sh
#
#workspaces="$(wmctrl -d)"
#windows_open="$(wmctrl -lx)"
#workspace_labels="$(echo "$workspaces" | awk '{print $9}')\n$(echo "$workspaces" | awk '{print $9}')"
##workspace_labels="$(echo "$workspaces" | awk '{print $9}')"
#current_workspace="$(echo "$workspaces" | awk '/\*/ {print $1}')"
#active_workspaces="$(echo "$windows_open" | awk '{print $2}')"
#
#echo "$windows_open"
#
#i=0
#monitor=0
#workspace_info="{\"0\":["
#open_in_monitor=0
#for workspace in $workspace_labels; do
#	cur_monitor=$((i / 10))
#	[ "$monitor" != $cur_monitor ] && workspace_info="${workspace_info%,}],\"$cur_monitor\":"
#	monitor=$cur_monitor
#	class="empty"
#	[ "$(echo "$active_workspaces" | grep -xc "$i")" -gt 0 ] && class="active"
#	[ "$i" = "$current_workspace" ] && class="current" && open_in_monitor="$cur_monitor"
#	workspace_info="$workspace_info{\"class\": \"$class\", \"index\": $i, \"label\": \"$workspace\"},"
#	i=$((i + 1))
#done
#echo "$workspace_info\"open_in_monitor\": $open_in_monitor}]"

