#!/usr/bin/perl
use warnings;
use strict;

my $workspaces_command = 'wmctrl -d';
my $workspaces = `$workspaces_command`;
die "system $workspaces_command failed: $?" if $?;

my $windows_on_workspaces_command = 'wmctrl -lx';
my $windows_on_workspaces = `$windows_on_workspaces_command`;
die "system $windows_on_workspaces_command failed: $?" if $?;

my @workspace_list = split("\n", $workspaces);

my @windows_on_workspaces_list = split("\n", $windows_on_workspaces);
my @active_workspaces = map { substr($_, 10, 3) } @windows_on_workspaces_list;

my @workspace_labels = map { (split(' ', $_))[-1] } @workspace_list;

my ($current_workspace) = grep { /\*/ } @workspace_list;
my $current_workspace_id = substr($current_workspace, 0, 2);

my @open_windows_info = grep { /$current_workspace_id/ } @windows_on_workspaces_list;

my @open_windows;
for(@open_windows_info) {
    my $third_element = (split(' ', $_))[2];
    my $last_element = (split('\.', $third_element))[-1];
    my %window = (
        id => substr($_, 0, 10),
		name => $last_element
    );
	push @open_windows, \%window;
}

my %workspaces_by_monitor;
my $open_in_monitor;

sub in_array {
	my ($needle, @haystack) = @_;
	for (@haystack) {
		$_ =~ s/\s+//g;
		if ($needle eq $_) {
			return 1;
		}
	}
	return 0;
}

my $index = 0;
for (@workspace_labels) {
	my $monitor = "_" . int($index / 10);
	my $class_name;

	unless (defined $workspaces_by_monitor{$monitor}) {
		$workspaces_by_monitor{$monitor} = ();
	}

	if ($index == $current_workspace_id) {
    	$class_name = "current";
		$open_in_monitor = $monitor;
	} elsif (in_array($index, @active_workspaces)) {
		$class_name = "active";
	} else {
		$class_name = "empty";
	}

	push @{$workspaces_by_monitor{$monitor}}, {
		"class" => $class_name,
		"index" => $index,
		"label" => $_,
	};
	$index++;
}

# Crappy json print, but works and doesn't require any modules

print "{";
print "\"open\": {";
for my $window (@open_windows) {
	print "\"id\": \"$window->{id}\", \"name\": \"$window->{name}\"";
}
print "},";
print "\"open_in_monitor\": \"". substr($open_in_monitor, 1) ."\",";
for my $monitor (keys %workspaces_by_monitor) {
	print '"' . substr($monitor, 1) . '": [';
	my $first = @{$workspaces_by_monitor{$monitor}}[0];
	print "{";
	print "\"class\": \"$first->{class}\",";
	print "\"index\": \"$first->{index}\",";
	print "\"label\": \"$first->{label}\"";
	print "}";
	for my $workspace (@{$workspaces_by_monitor{$monitor}}[1..$#{$workspaces_by_monitor{$monitor}}]) {
		print ",{";
		print "\"class\": \"$workspace->{class}\",";
		print "\"index\": \"$workspace->{index}\",";
		print "\"label\": \"$workspace->{label}\"";
		print "}";
	}
	print "]";
}
print "}\n"
