#!/bin/sh

bsp_monitors()
{
	#HDMI and VGA
	# if [[ $(xrandr -q | grep DP-2 | grep " connected") ]] && [[ $(xrandr -q | grep HDMI-1 | grep " connected") ]]
	# then
	# 	bspc monitor eDP-1 -d 1 2 3 4
	# 	bspc monitor DP-2 -d 5 6 7
	# 	bspc monitor HDMI-1 -d 8 9 0
	# 	xrandr --output DP-2 --auto --right-of eDP-1
	# 	xrandr --output HDMI-1 --auto --left-of eDP-1
	# #VGA
	# elif [[ $(xrandr -q | grep DP-2 | grep " connected") ]]
	# then
	# 	bspc monitor "eDP-1" -d 1 2 3 4
	# 	bspc monitor "DP-2" -d 5 6 7 8 9 0
	# 	xrandr --output "DP-2" --auto --right-of "eDP-1"
	# #HDMI
	# elif [[ $(xrandr -q | grep HDMI-1 | grep " connected") ]] then
	# 	bspc monitor eDP-1 -d 7 8 9 0
	# 	bspc monitor HDMI-1 -d 1 2 3 4 5 6
	# 	xrandr --output HDMI-1 --auto --left-of eDP-1
	# #NONE
	# else
		#bspc monitor -d 1 2 3 4 5 6 7 8 9 0
		bspc monitor -d "一" "二" "三" "四" "五" "六" "七" "八" "九" "十"
	#fi
}

#wal colors
# source the colors.
[ -f "${HOME}/.cache/wal/colors.sh" ] && . "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config active_border_color 		"$color1"
# bspc config focused_border_color 		"$color12"
bspc config focused_border_color 		"#541140"
# bspc config normal_border_color 		"$color8"
bspc config normal_border_color 		"#4f4f4f"

# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color 		"$color1"

bspc config top_padding 				50
bspc config bottom_padding 				0
bspc config border_width				4
bspc config window_gap 					20
bspc config split_ratio          		0.5
bspc config borderless_monocle   		false
bspc config gapless_monocle      		false
bspc config single_monocle				true
bspc config pointer_modifier 			mod4
bspc config pointer_action1				move
bspc config pointer_action2				resize_corner
bspc config focus_follows_pointer   	true
bspc config presel_feedback_color 		"#51c4d4"

# [ Initialize monitors acording to what is plugged ]
bsp_monitors
#bspc monitor -d 1 2 3 4 5 6 7 8 9 0

xsetroot -cursor_name left_ptr

# [Rules for applications]
bspc config ignore_ewmh_focus true

bspc rule -a firefox                     desktop=^2  follow=off
bspc rule -a "Vivaldi-stable"            desktop=^2  follow=off
bspc rule -a "Brave-browser"             desktop=^2  follow=off
bspc rule -a qutebrowser                 desktop=^2  follow=off
bspc rule -a Gimp                        desktop=^3  follow=off
bspc rule -a krita                       desktop=^3  follow=off
bspc rule -a shotcut                     desktop=^3  follow=off
bspc rule -a Telegram                    desktop=^4  follow=off
bspc rule -a thunderbird                 desktop=^4  follow=off
bspc rule -a "notion-calendar-electron"  desktop=^4  follow=off
bspc rule -a zoom                        desktop=^5  follow=off state=floating sticky=off
bspc rule -a discord                     desktop=^6  follow=off
bspc rule -a Slack                       desktop=^6  follow=off
bspc rule -a "transmission"              desktop=^8  follow=off state=pseudo_tiled
bspc rule -a DBeaver                     desktop=^9  follow=off
bspc rule -a beekeeper-studio            desktop=^9  follow=off
bspc rule -a Spotify                     desktop=^10 follow=off
bspc rule -a elisa                       desktop=^10 follow=off

bspc rule -a feh                         floating=on center=true follow=off
bspc rule -a "screengrab"                floating=on center=true follow=off
bspc rule -a calendar                    desktop=^5 state=floating
bspc rule -a "Emacs"                     state=tiled

# scratchpad
bspc rule -a dropdown sticky=on state=floating hidden=on

# class for floating windows
bspc rule -a Floating state=floating
bspc rule -a Tasklist state=floating

startup_progs
