#!/bin/sh

#wal colors
# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config active_border_color 		"$color1"
bspc config focused_border_color 		"$color2"
bspc config normal_border_color 		"$color15"

# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color 		"$color1"

bspc config top_padding 				20
bspc config bottom_padding 				0
bspc config border_width				2
bspc config window_gap 					$GAPS
bspc config split_ratio          		0.5
bspc config borderless_monocle   		true
bspc config gapless_monocle      		true
bspc config pointer_modifier 			mod1
bspc config pointer_action1				move
bspc config pointer_action2				resize_side
bspc config focus_follows_pointer   	true
bspc config presel_feedback_color 		"#51c4d4"

if [[ $(xrandr -q | grep DP2 | grep " connected") ]]
then
	bspc monitor eDP1 -d 1 2 3 4
	bspc monitor DP2 -d 5 6 7 8 9 0
	xrandr --output DP2 --auto --right-of eDP1
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

xwallpaper --output all --stretch ~/.config/wall.jpg
xsetroot -cursor_name left_ptr

# [Rules for applications]

bspc config ignore_ewmh_focus true

bspc rule -a firefox 				desktop=^2 	follow=off
bspc rule -a "Vivaldi-stable"		desktop=^2 	follow=off
bspc rule -a qutebrowser 			desktop=^2 	follow=off
bspc rule -a gimp 					desktop=^3 	follow=off
bspc rule -a krita 					desktop=^3 	follow=off
bspc rule -a gimp 					desktop=^3 	follow=off
bspc rule -a Telegram 				desktop=^4 	follow=off
bspc rule -a discord				desktop=^4 	follow=off
bspc rule -a mpv 					desktop=^5 	follow=off fullscreen=on 
bspc rule -a "Transmission-gtk" 	desktop=^5  follow=off
bspc rule -a Spotify 				desktop=^10 follow=off
bspc rule -a feh 					floating=on center=true follow=off

# scratchpad
bspc rule -a dropdown sticky=on state=floating hidden=on

set_colors
launch_polybar.sh
startup_progs.sh
