#!/bin/sh

eww_bar_config="$HOME/.config/eww/left-bar"
eww -c "$eww_bar_config" close-all

monitor_count=$(xrandr --listactivemonitors | head -n 1 | awk '{print $2}')

for i in $(seq 0 "$((monitor_count - 1))"); do
	echo "Starting eww left-bar-$i on monitor $i"
	eww -c "$eww_bar_config" open leftbar --id "left-bar-$i" --screen "$i" &
done
