#!/bin/bash

#Notes CRUD
#script for taking simple notes in the terminal

if [ ! $NOTES_PATH ];then
	NOTES_PATH="$HOME/.scripts/"
fi

add_note()
{
	NOTE=$1
	shift
	if [ $1 ]; then
		TAG=$1
		shift
	else
		TAG=""
	fi

	if [ ! -f $NOTES_PATH.notes$TAG ]; then
		touch $NOTES_PATH.notes$TAG
	fi
	read NOTE_NUMBER<<<$(awk 'END{print $1}' $NOTES_PATH.notes$TAG | sed s/~//g)
	NOTE_NUMBER=$((NOTE_NUMBER+1))
	DATE=`date +%Y-%m-%d`
	echo "~$NOTE_NUMBER	$DATE	'$NOTE'">>$NOTES_PATH.notes$TAG
}

list_notes()
{
	if [ $1 ]; then
		if [ $1 == -d ]; then
			WHICH_NOTES=".notes";shift
		else
			WHICH_NOTES=".notes$1"; shift
		fi
	else
		WHICH_NOTES=$(ls -a $NOTES_PATH | grep ^.notes | dmenu -l 10)
	fi

	if test -f $NOTES_PATH$WHICH_NOTES; then
		awk -F "\t" '{print $1". " $3}' $NOTES_PATH$WHICH_NOTES
	else
		echo 'No Notes'
	fi
}

filter_notes()
{
	if [ $1 ]; then
		if [ $1 == -d ]; then
			WHICH_NOTES=".notes";shift
		else
			WHICH_NOTES=".notes$1"; shift
		fi
	else
		WHICH_NOTES=$(ls -a $NOTES_PATH | grep ^.notes | dmenu -l 10)
	fi

	if test -f $NOTES_PATH$WHICH_NOTES; then
		cat $NOTES_PATH$WHICH_NOTES | grep "$1" | awk -F "\t" '{print $1. "\033[34m "$3"\033[0m"}'
		shift
	else
		echo 'No Notes'
	fi
}

show_help()
{
	echo 'aNote [SOME NOTE] [SOME TAG]: Adds a note to a specific Tag. If no tag is informed adds to general notes'
	echo 'aNote -l [SOME TAG]:Prompts with a dmenu to select notes file to list notes from
					-d flag to list general notes'
	echo 'aNote -f [WORD/DATE]: Search for notes with that word, tag or date'
	echo 'aNote -r [TAG]: prompts with a dmenu to select note to delete. if no tag is informed dmenu prompts with tag and then 			notes'
}

remove_note()
{
	if [ $1 ]; then
		if [ $1 == -d ]; then
			WHICH_NOTES=".notes";shift
		else
			WHICH_NOTES=".notes$1"; shift
		fi
	else
		WHICH_NOTES=$(ls -a $NOTES_PATH | grep ^.notes | dmenu -l 10)
	fi

	if test -f "$NOTES_PATH$WHICH_NOTES"; then
		NOTE=$(cat $NOTES_PATH$WHICH_NOTES | sed "s/	/ /g" | dmenu -l 10 | awk -F " " '{print $1}')
		sed -i '/'"$NOTE"'/d' $NOTES_PATH$WHICH_NOTES
		ALL_NOTES=$(cat $NOTES_PATH$WHICH_NOTES)
		if [ ! "$ALL_NOTES" ]; then
			rm $NOTES_PATH$WHICH_NOTES
		fi
	else
		echo 'No Notes'
	fi
}

case $1 in
	-l) shift; list_notes "$1"
		;;
	-f) shift; filter_notes "$1"
		;;
	-h) show_help
		;;
	-r) shift; remove_note "$1"
		;;
	*) add_note "$1" "$2"
		;;
esac
