#!/bin/bash

#Conta quanto tempo a bateria esta durando, por dia, de acordo com o tempo que ela esta descarregando
STATUS=$(cat /sys/class/power_supply/BAT0/status)
STATUS1=$(cat /sys/class/power_supply/BAT1/status)

date=`date '+%y-%m-%d'`

FINAL_STATUS=''
if [  $STATUS == 'Discharging' ] || [ $STATUS1 == 'Discharging' ]; then
	FINAL_STATUS='Discharging'
fi

if [ $FINAL_STATUS == 'Discharging' ]
then
	if [ -e ~/.battime/"$date"_1 ]; then
		echo $((`cat ~/.battime/"$date"_1`+1)) > ~/.battime/"$date"
	else
		echo $((`cat ~/.battime/"$date"`+1)) > ~/.battime/"$date"
	fi
else
	echo 1 > ~/.battime/"$date"_1
fi

