#!/bin/sh
# Notifica quando a bateria estah abaixo de 5%
#export DBUS_SESSION_BUS_ADDRESS eh da versao antiga que rodava no cron

COUNT="$(ls /sys/class/power_supply/ | wc -w)"
PERCENT="$(cat /sys/class/power_supply/*/capacity | paste -sd '+')"
STATUS="$(cat /sys/class/power_supply/*/status)"

#Count -1 to ignore AC
TOTAL=$(( PERCENT / (COUNT-1) ))

FINAL_STATUS='Charging'
[ "$(echo $STATUS | grep Discharging)" ] && FINAL_STATUS='Discharging'

[ $TOTAL -lt 10 ] && [ "$FINAL_STATUS" == 'Discharging' ] &&
#export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus &&
export DISPLAY=:0.0 &&	
notify-send -u critical "Battery low" "Battery at $TOTAL%" &&
beep
