#!/bin/sh
# Notifica quando a bateria estah abaixo de 5%
#export DBUS_SESSION_BUS_ADDRESS eh da versao antiga que rodava no cron

PERCENT=$(cat /sys/class/power_supply/BAT0/capacity)
STATUS=$(cat /sys/class/power_supply/BAT0/status)
if [ $PERCENT -lt 5 ] && [ $STATUS == 'Discharging' ]; then
	beep
	export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus &&
	notify-send -u critical "Battery low" "Battery at $PERCENT"
fi
