#!/bin/bash

# rotate all horizontal splits to be vertical
for id in $(bspc query -T -d | jq -r '.. | objects | select( has("splitType")) | { id: .id, splitType: .splitType } | select( .splitType == "horizontal" ) | .id'); do
  bspc node "$id" --rotate 90
done

# balance the window sizes
bspc node @/ --balance

