#!/bin/sh
# Notify me with notify-send if my battery is below 20%.
# You can set this to run via cron.
#exports DBUS SESSION to work in cron
PERCENT=$(cat /sys/class/power_supply/BAT0/capacity)
STATUS=$(cat /sys/class/power_supply/BAT0/status)
if [ $PERCENT -lt 20 ] && [ $STATUS == 'Discharging' ]; then
	export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus &&
	notify-send -u critical "Battery low" "Battery at $PERCENT"
fi
