#!/bin/bash

#-Simple bar script for DWM


bar()
{
	separator='|'

	#keyboard layout
	#layout=$(setxkbmap -query | grep layout | awk '{ print $2 }')
	layout=$(xset -q | grep LED | awk '{ print $10 }')
	case "$layout" in
		"00000000" | "00000001" | "00000002") layout="us";;
		"00001000" | "00001001" | "00001002") layout="br";;
	esac

	echo "$layout $separator"

	#battery

	echo "$(batstatus)% $separator"

	#calculates the brightness in percent
	brightness=$(cat /sys/class/backlight/*/brightness)
	max=$(cat /sys/class/backlight/*/max_brightness)
	#uses python3 to get decimals
	l=$(echo "print($brightness/$max*100)" | python3)
	light=" ${l%.*}"
	echo "$light% $separator"

	
	#volume
	vol="$(pamixer --get-volume-human)"
	if [ "$vol" == "muted" ];then
		vol=" $vol"
	else
		vol=" $vol"
	fi
	echo "$vol $separator"


	date '+%Y %b %d %I:%M%p'
	
	echo "$separator"

	#wifi
	wifi=$(nmcli | grep ' connected' | awk '{for(i=2; i<= NF; i++) printf $i" "}')
	if [ -z "$wifi" ];then
		echo "Disconnected"
	else
		echo $(echo "$wifi" | sed 's/connected to//' )
	fi

}

while :; do
	xsetroot -name "$(bar | tr '\n' ' ')"

	sleep 30
done
