#!/bin/bash

#-Locks the screen, pauses songs and videos.

# Pause music (mocp, mpd and send the pause key to all mpv videos):

# Pause music (mocp, mpd and send the pause key to all mpv videos):
dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Pause
mocp -P &>/dev/null
mpc pause &>/dev/null
pauseallmpv &>/dev/null

slock &

# In five seconds, turn off display unless key press in last 4 seconds.
sleep 5 && [[ 4000 -lt $(xssstate -i) ]] &&  pgrep -x slock && xset dpms force off

# How long screen was locked
if [ $1 == -s ]
then
	t=0
	while [ "$(pgrep slock)" ]
	do
		sleep 1m
		t=$((t+1))
	done
	ocioso=0
	if [ -f /tmp/ocioso ]; then
		ocioso=$(cat /tmp/ocioso)
		t=$((t + ocioso))
	else
		touch /tmp/ocioso
	fi
	
	if [ "$t" -gt 10 ]; then 
    	notify-send "$t"
    	echo "$((t - 10 ))" > /tmp/ocioso
	fi
fi

