#!/bin/bash

#-Helper for dealing with multiple monitors, works via dmenu

list_mon()
{
	xrandr -q | grep " connected" | awk '{print $1}' | tail -n +2
}

list_opt()
{
	printf "%s\n%s\n%s\n%s\n%s\n%s\n" \
		"--right-of"\
		"--left-of" \
		"--above"   \
		"--below"   \
		"--same-as" \
		"--off"
}

OUT=$(list_mon | dmenu -l 6)
[ "$OUT" ] && OPT=$(list_opt | dmenu -l 6) || exit

if [ "$OPT" == "--off" ]
then
	xrandr --output $OUT $OPT
else
	xrandr --output $OUT --auto $OPT eDP1
fi

[ "$(pgrep bspwm)" ] && bspc wm -r
