#!/bin/bash
 
select_mon()
{
	MONITOR=$(xrandr | grep -s ' connected' | awk '{print $1}' | dmenu -l 5)
}

advanced_ops()
{
	OPTION=$(printf "--left-of\n--right-of\n--above\n--below\n--same-as" | dmenu -l 5)
	MONITORB=$(xrandr | grep ' connected' | awk '{print $1}' | dmenu -l 5)

	OPTION=$OPTION" "$MONITORB
	
}

turn_off()
{
	MONITOR=$(xrandr | grep ' connected' | awk '{print $1}' | dmenu -l 5)
	xrandr $MONITOR --off
}

show_help()
{
	echo "Usage: displays";
	echo "       displays -a: Show advanced options";
	echo "       displays -o: Turn off a monitor";
	echo "       displays -h: Shows help";
}

ACTIVE=$(xrandr | grep)
OPTION=''


case $1 in
	-a) shift; select_mon
		advanced_ops
		;;
	-o) shift; turn_off
		;;
	-h) shift; show_help
		;;
	*)	shift; select_mon
		;;
esac

if [ $MONITOR ]; then
	xrandr --output $MONITOR $OPTION --auto
fi

