#!/bin/bash

#-Records my screen to a file in ~/

SIZE=$(xrandr | grep eDP1 | awk '{print $4}' | sed 's/+0+0//')
DATE=`date +%Y-%m-%d`

ffmpeg -f x11grab \
	-s $SIZE \
	-i :0.0 \
	-f alsa -i default \
	-c:v libx264 -r 30 -c:a flac screencast-$DATE.mkv
