#!/bin/bash

BG="$HOME/repos/wallpapers/OOORiver-normlCloud.jpg"
[ $1 ] && BG="$1"

wal -t -n -i "$BG"

#for some reason .config/wall.jpg was always getting the old one, maybe because of cache
#rewrite line 5 with $1 to set default
#Escape / in $HOME
[ "$1" ] &&
old=$(echo 'BG="$HOME/repos/wallpapers/OOORiver-normlCloud.jpg"' | sed  's/\//\\\//g') &&
new=$(echo 'BG="$HOME/'"$1"'"' | sed  's/\//\\\//g') &&
sed -i "s/$old/$new/g" $HOME/.scripts/set_colors

#Make a file that can acctualy be used for dwm
cp $HOME/.cache/wal/colors-wal-dwm.h $HOME/.cache/wal/colors-wal-dwm-real.h
sed -i "s/\[SchemeNorm\] = //g" $HOME/.cache/wal/colors-wal-dwm-real.h
sed -i "s/\[SchemeSel\]  = //g" $HOME/.cache/wal/colors-wal-dwm-real.h
sed -i "s/\[SchemeUrg\] = //g" $HOME/.cache/wal/colors-wal-dwm-real.h
