#!/bin/bash

#-runs programs after wm is setup
#-avoids any errors that might occur if a program runs before another one
#-Example: if transmission-gtk runs before bspwm rules are set it will open on workspace 1

#System colors and wallpaper
set_colors 
set_colors -w

#Wifi connection
nm-applet &
#Hide that damn mouse when it is idle
unclutter &

#Load specific WM configs
if [ "$(pgrep -x bspwm)" ]; then
	cat $CONFIG/sxhkd/base $CONFIG/sxhkd/bspwm_keys > $CONFIG/sxhkd/sxhkdrc
elif [ "$(pgrep -x dwm)" ]; then 
	cat $CONFIG/sxhkd/base $CONFIG/sxhkd/dwm_keys > $CONFIG/sxhkd/sxhkdrc &&
	dwmbar &
elif [ "$(pgrep -x i3)" ]; then
	cat $CONFIG/sxhkd/base $CONFIG/sxhkd/i3_keys > $CONFIG/sxhkd/sxhkdrc
fi
sxhkd &

#Seed torrents, like a good boy
[ ! "$(pgrep -x transmission-qt)" ] && transmission-qt &
#Notifications
dunst &
#Utterly amazing transparent terminals
compton &
#Let me use pt-br and en-us keyboards
keyboard_layout &
#Don't burn my eyes
toggle_redshift
#Remind of my stuff
shownotes
#Tell me if i need to update
must_update
