#!/bin/bash
#copies config folder and other files to git repository
CONFIG_DIR="/home/lucca/.config"
REPO="/home/lucca/Repos/RICE"
echo "Copying .config folders"
cp -r $CONFIG_DIR/compton.conf $REPO/.config
cp -r $CONFIG_DIR/dconf $REPO/.config
cp -r $CONFIG_DIR/dunst $REPO/.config
cp -r $CONFIG_DIR/feh $REPO/.config
cp -r $CONFIG_DIR/fontconfig $REPO/.config
cp -r $CONFIG_DIR/gconf $REPO/.config
cp -r $CONFIG_DIR/i3 $REPO/.config
cp -r $CONFIG_DIR/neofetch $REPO/.config
cp -r $CONFIG_DIR/newsboat $REPO/.config
cp -r $CONFIG_DIR/pcmanfm $REPO/.config
cp -r $CONFIG_DIR/polybar $REPO/.config
cp -r $CONFIG_DIR/QtProject.conf $REPO/.config
cp -r $CONFIG_DIR/qutebrowser $REPO/.config
cp -r $CONFIG_DIR/ranger $REPO/.config
cp -r $CONFIG_DIR/spotify $REPO/.config
cp -r $CONFIG_DIR/transmission $REPO/.config
cp -r $CONFIG_DIR/vlc $REPO/.config
cp -r $CONFIG_DIR/wal $REPO/.config
cp -r $CONFIG_DIR/wall.jpg $REPO/.config
cp -r $CONFIG_DIR/zathura $REPO/.config
echo "Copying vim, urxvt,scripts and bash files"
cp -r /home/lucca/.scripts $REPO
cp -r /home/lucca/.vim $REPO
cp -r /home/lucca/.time $REPO
cp /home/lucca/.vimrc $REPO
cp /home/lucca/.bash_aliases $REPO
cp /home/lucca/.bash_profile $REPO
cp /home/lucca/.bashrc  $REPO
cp /home/lucca/.Xresources $REPO
cp /home/lucca/.xinitrc $REPO

cd $REPO
#update programs list
LIST=$(pacman -Sl); for ARG in $(pacman -Qq); do echo "$LIST" | grep " $ARG "; done | awk '{print $2}' > progs.txt
 
#add new scripts
cd $REPO
git add .
git commit -a
git push
cd /home/lucca/


