#!/bin/bash
#copies config folder and other files to git repository
CONFIG_DIR="/home/lucca/.config"
REPO="/home/lucca/Repos/RICE"
echo "Copying .config folders"
cp -r $CONFIG_DIR/* $REPO/.config
echo "Copying vim, urxvt,scripts and bash files"
cp -r /home/lucca/.scripts/* $REPO/.scripts
cp -r /home/lucca/.vim $REPO
cp /home/lucca/.vimrc $REPO
cp /home/lucca/.bash_aliases $REPO
cp /home/lucca/.bash_profile $REPO
cp /home/lucca/.bashrc  $REPO
cp /home/lucca/.Xresources $REPO
cp /home/lucca/.Xauthority $REPO

cd $REPO
#add new scripts
cd .scripts
git add .
git commit -a
git push
cd /home/lucca/
