#!/bin/bash
#copies config folder and other files to git repository
CONFIG_DIR="/home/lucca/.config"
REPO="/home/lucca/Repos/RICE"
echo "Copying .config folders"
cp -r $CONFIG_DIR/compton.conf $REPO/.config
cp -r $CONFIG_DIR/dconf $REPO/.config
cp -r $CONFIG_DIR/dunst $REPO/.config
cp -r $CONFIG_DIR/feh $REPO/.config
cp -r $CONFIG_DIR/fontconfig $REPO/.config
cp -r $CONFIG_DIR/fontforge $REPO/.config
cp -r $CONFIG_DIR/gconf $REPO/.config
cp -r $CONFIG_DIR/i3 $REPO/.config
cp -r $CONFIG_DIR/neofetch $REPO/.config
cp -r $CONFIG_DIR/newsboat $REPO/.config
cp -r $CONFIG_DIR/pcmanfm $REPO/.config
cp -r $CONFIG_DIR/QtProject.conf $REPO/.config
cp -r $CONFIG_DIR/qutebrowser $REPO/.config
cp -r $CONFIG_DIR/ranger $REPO/.config
cp -r $CONFIG_DIR/spotify $REPO/.config
cp -r $CONFIG_DIR/sxhkd $REPO/.config
cp -r $CONFIG_DIR/transmission $REPO/.config
cp -r $CONFIG_DIR/vlc $REPO/.config
cp -r $CONFIG_DIR/wal $REPO/.config
cp -r $CONFIG_DIR/wall.jpg $REPO/.config
cp -r $CONFIG_DIR/zathura $REPO/.config
echo "Copying vim, scripts and bash files"
cp $HOME/.bash_aliases $REPO
cp $HOME/.bash_logout $REPO
cp $HOME/.bash_profile $REPO
cp $HOME/.bashrc  $REPO
cp -r $HOME/.scripts $REPO
cp -r $HOME/.vim $REPO
cp -r $HOME/.time $REPO
cp $HOME/.vimrc $REPO
cp $HOME/.Xresources $REPO
cp $HOME/.xinitrc $REPO
cp $HOME/.xprofile $REPO

cd $REPO
#update programs list
#LIST=$(pacman -Sl); for ARG in $(pacman -Qq); do echo "$LIST" | grep " $ARG "; done | awk '{print $2}' > progs.txt
pacman -Qq > progs.txt
 
#add new scripts
cd $REPO
git add .
git commit -a
git push
cd $HOME
