#!/bin/bash

RICE=$HOME/repos/rice
CONFIG=$HOME/.config
AQUI=$PWD

echo "Cleaning Repository to delete old files. (Dotfiles only)"
rm $RICE/.* > /dev/null 2>&1

echo "copying home files"
cp $HOME/.bash_aliases $RICE
cp $HOME/.bash_profile $RICE
cp $HOME/.bashrc $RICE
cp $HOME/.vimrc $RICE
cp $HOME/.xinitrc $RICE
cp $HOME/.xprofile $RICE
cp $HOME/.Xresources $RICE
cp $HOME/.tmux.conf $RICE

echo "copying home directories"
cp -r $HOME/.vim $RICE
cp -r $HOME/.vimgolf $RICE
cp -r $HOME/.scripts $RICE
cp -r $HOME/.time $RICE

echo "copying .config files"
cp $CONFIG/kritadisplayrc $RICE/.config
cp $CONFIG/kritarc $RICE/.config
cp $CONFIG/kritashortcutsrc $RICE/.config
cp $CONFIG/wall.jpg $RICE/.config
cp -r $CONFIG/i3 $RICE/.config
cp -r $CONFIG/i3status $RICE/.config
cp -r $CONFIG/bspwm $RICE/.config
cp -r $CONFIG/polybar $RICE/.config
cp -r $CONFIG/pulse $RICE/.config
cp -r $CONFIG/ranger $RICE/.config
cp -r $CONFIG/redshift $RICE/.config
cp -r $CONFIG/sxhkd $RICE/.config
cp -r $CONFIG/transmission $RICE/.config
cp -r $CONFIG/wal $RICE/.config
cp -r $CONFIG/mpd $RICE/.config
cp -r $CONFIG/ncmpcpp $RICE/.config

cd $RICE
echo "Adding new files to repo"
git add .
[ "$1" ] && 
echo "Comitting changes" &&
git commit -m "$1" &&
echo "Pushing changes" && 
git push
cd $AQUI
